<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <EnableComHosting>true</EnableComHosting>
    <GenerateComHost>true</GenerateComHost>
    <ComVisible>true</ComVisible>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ComHostingSupported>true</ComHostingSupported>
    <AssemblyManifest>HelloWorldLib.manifest</AssemblyManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelloWorldLib.Interop\HelloWorldLib.Interop.csproj" />
  </ItemGroup>

</Project>
